package com.umldesigner.activities.uml_activity.STable;

import android.util.Log;
import android.util.Pair;
import androidx.recyclerview.widget.RecyclerView;
import com.umldesigner.activities.uml_activity.SFK.SFKView;
import com.umldesigner.activities.uml_activity.SItem.SItemData;
import com.umldesigner.infrastructure.uml.data.BaseDataInterface;
import com.umldesigner.infrastructure.uml.logic.app.observer.BaseObservable;
import com.umldesigner.infrastructure.uml.logic.app.observer.BaseObserver;
import com.umldesigner.infrastructure.uml.utils.SUtils;
import com.umldesigner.submodules.UmlDesignerShared.schema.table.dto.STablePojo;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/**
 * data field used exclusively for android
 */
public class STableData extends STablePojo implements BaseDataInterface, BaseObservable {
    @Getter
    private final HashSet<SFKView> foreignKeys = new HashSet<>();
    
    @Getter
    private final Integer id;
   
    @Getter
    @Setter
    private RecyclerView recyclerView; //this is used for getting stuff for the sfk

   private STableData(Integer id, String uuid, float x, float y,
                      String title, List<SItemData> items){
       this.id = id != null ? id : SUtils.getInstance().getNextId();
       this.uuid = uuid;
       this.x = x;
       this.y = y;
       this.title = title;
       this.items = items != null ? items : new ArrayList<>();
   }

    /**
     * generates new instance from the given fields
     * @param id id of the table, used for differentiating tables in the app side of things, if null will be autogenerated
     * @param uuid unique id used for backend side of things
     * @param x absolute position
     * @param y absolute position
     * @param title of the table
     * @param items inside the table, if left null new list with no items will be generated
     * @return new instance
     */
   public static STableData newInstance(Integer id, String uuid, float x, float y, @NonNull String title,
                                       List<SItemData> items){
       if(x < 0 || y < 0){
           throw new IllegalArgumentException("negative positions are not accepted," +
                   "if using an empty instance (see constructor newEmptyInstance) make sure that the all the fields" +
                   "are valid");
       }

       return new STableData(
               id,
               uuid,
               x,
               y,
               title,
               items
       );
   }

    /**
     * creates instance with no given fields and is unstable,
     * should be avoided if possible, if creation of empty instance cannot be avoided,
     * it should be recreated with {@link #newInstance(Integer, String, float, float, String, List)} as soon as possible
     * @see #newInstance(Integer, String, float, float, String, List)
     * @return empty instance
     */
   public static STableData newEmptyInstance() {
       return new STableData(
               null,
               null,
               -1,
               -1,
               null,
               null
       );
   }

    public static STableData from(STablePojo tableData) {

       if(tableData == null){
           return null;
       }

       /*
            warning is suppressed because in backend SItemData/STaleData etc. are used and to create those it is forced
            to provide *data of those classes instead of the pojo
        */
        List<SItemData> items = new ArrayList<>();
        if(tableData.getItems() != null){
            @SuppressWarnings("unchecked")
            List<SItemData> tableItems = (List<SItemData>) tableData.getItems();
            items.addAll(tableItems);
        }

        return new STableData(
                null,
                tableData.getUuid(),
                tableData.getX(),
                tableData.getY(),
                tableData.getTitle(),
                items
        );
    }

    /**
     *
     * @return data of items, if null will return empty List
     */
    public List<SItemData> getItems(){
        if(super.getItems() == null){
            return null;
        }

        /*
        warning is suppressed because in backend SItemData/STaleData etc. are used and to create those it is forced
        to provide *data of those classes instead of the pojo
        */
        @SuppressWarnings("unchecked")
        List<SItemData> itemData = (List<SItemData>) super.getItems();
        if (itemData.isEmpty()){
            itemData = new ArrayList<>();
        }
        return itemData;
    }

    /**
     * sets the x position in the data and updates the itemData n stuff
     * @param x
     */
    
    @Override
    public void setX(Float x) {
        super.setX(x);
    }
    
    @Override
    public void setY(Float y) {
        super.setY(y);
    }
    
    @Override
    public void registerObserver(BaseObserver o) {
        Log.d("Execute", "registerObserver: ");
        foreignKeys.add((SFKView) o);
    }
    
    @Override
    public void removeObserver(BaseObserver o) {
        Log.d("Execute", "removeObserver: " + o.toString());
        foreignKeys.remove((SFKView) o);
    }
    
    @Override
    public void notifyObservers() {
        Log.d("Execute", "notifyObservers: ");
        STableDataBuffer sTableDataBuffer = new STableDataBuffer();
        for(SFKView sfk : foreignKeys){
            sfk.updateObserver(this, sTableDataBuffer);
        }
        
        for(int i = 0; i < sTableDataBuffer.getCount(); i++){
            Pair<SFKView, SFKView> curValue = sTableDataBuffer.getBuffer().get(i);
            
            //destroying the observer, NOTE removeObserver is called from inside the destroy method
            assert curValue != null;
            curValue.first.destroy();
    
            //saving the new key's
            curValue.first.getSTableData().registerObserver(curValue.second);
            curValue.first.getFTableData().registerObserver(curValue.second);
        }
    }
}
