package com.umldesigner.activities.uml_activity.STable;

import android.util.Log;
import android.util.Pair;
import androidx.recyclerview.widget.RecyclerView;
import com.umldesigner.activities.uml_activity.SFK.SFKView;
import com.umldesigner.activities.uml_activity.SItem.SItemData;
import com.umldesigner.infrastructure.uml.data.BaseDataInterface;
import com.umldesigner.infrastructure.uml.logic.app.observer.BaseObservable;
import com.umldesigner.infrastructure.uml.logic.app.observer.BaseObserver;
import com.umldesigner.infrastructure.uml.utils.SUtils;
import com.umldesigner.submodules.UmlDesignerShared.schema.table.dto.STablePojo;
import com.umldesigner.submodules.UmlDesignerShared.schema.table_item.dto.SItemPojo;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * data field used exclusively for android
 */
public class STableData implements BaseDataInterface<STablePojo>, BaseObservable{

    @Getter
    private final STablePojo pojo;
    @Getter
    private final HashSet<SFKView> foreignKeys = new HashSet<>();
    
    @Getter
    private final Integer id;
   
    @Getter
    @Setter
    private RecyclerView recyclerView; //this is used for getting stuff for the sfk

   private STableData(Integer id, String uuid, float x, float y,
                      String title, List<SItemData> items){
       this.id = id != null ? id : SUtils.getInstance().getNextId();

       //basically getting the pojo of each item and turning that into a list
       List<SItemPojo> castedPojos = items.stream().map(SItemData::getPojo).collect(Collectors.toList());
       this.pojo = new STablePojo(title, castedPojos, uuid, x, y);
   }

    /**
     * generates new instance from the given fields
     * @param id id of the table, used for differentiating tables in the app side of things, if null will be autogenerated
     * @param uuid unique id used for backend side of things
     * @param x absolute position
     * @param y absolute position
     * @param title of the table
     * @param items inside the table, if left null new list with no items will be generated
     * @return new instance
     */
   public static STableData newInstance(Integer id, String uuid, float x, float y, @NonNull String title,
                                       List<SItemData> items){
       if(x < 0 || y < 0){
           throw new IllegalArgumentException("negative positions are not accepted," +
                   "if using an empty instance (see constructor newEmptyInstance) make sure that the all the fields" +
                   "are valid");
       }

       return new STableData(
               id,
               uuid,
               x,
               y,
               title,
               items
       );
   }

    /**
     * creates instance with no given fields and is unstable,
     * should be avoided if possible, if creation of empty instance cannot be avoided,
     * it should be recreated with {@link #newInstance(Integer, String, float, float, String, List)} as soon as possible
     * @see #newInstance(Integer, String, float, float, String, List)
     * @return empty instance
     */
   public static STableData newEmptyInstance() {
       return new STableData(
               null,
               null,
               -1,
               -1,
               null,
               null
       );
   }

    public static STableData from(STablePojo tableData) {

        if (tableData == null) {
            return null;
        }

       /*
            warning is suppressed because in backend SItemData/STaleData etc. are used and to create those it is forced
            to provide *data of those classes instead of the pojo
        */
        List<SItemData> items = new ArrayList<>();
        if (tableData.getItems() != null) {
            /*
                we are converting pojo to data so its items should be pojo's as well
             */
            @SuppressWarnings("unchecked")
            List<SItemPojo> tableItems = (List<SItemPojo>) tableData.getItems();
            for(SItemPojo itemPojo : tableItems){
                items.add(SItemData.from(itemPojo));
            }
        }

        return new STableData(
                null,
                tableData.getUuid(),
                tableData.getX(),
                tableData.getY(),
                tableData.getTitle(),
                items
        );
    }

    /**
     *
     * @return data of items, if null will return empty List
     */
    public List<SItemData> getItems(){
        if(pojo.getItems() == null){
            return null;
        }

        /*
        warning is suppressed because in backend SItemData/STaleData etc. are used and to create those it is forced
        to provide *data of those classes instead of the pojo
        */
        @SuppressWarnings("unchecked")
        List<SItemData> itemData = (List<SItemData>) pojo.getItems();
        if (itemData.isEmpty()){
            itemData = new ArrayList<>();
        }
        return itemData;
    }

    /**
     * @param uuid uuid of the item
     * @return item by its uuid or null if it doesn't exist in the current table
     */
    public SItemData getItemByUuid(String uuid){
        List<SItemData> items = getItems();
        for(SItemData item : items){
            if(uuid.equals(item.getPojo().getUuid())){
                return item;
            }
        }
        return null;
    }

    /**
     * finds item position by given item uuid
     * @param uuid uuid of the item
     * @return position in the items list of the item
     */
    public int getItemPosition(String uuid){
        return getItems().indexOf(getItemByUuid(uuid));
    }

    /**
     * finds item position of the given item
     * @param item the given item
     * @return the position of the item in the items list
     */
    public int getItemPosition(SItemData item){
        return getItems().indexOf(item);
    }

    public String getUuid(){
        return pojo.getUuid();
    }

    public Float getX(){
        return pojo.getX();
    }

    public Float getY(){
        return pojo.getY();
    }

    public void setX(Float x) {
        pojo.setX(x);
    }
    
    public void setY(Float y) {
        pojo.setY(y);
    }
    
    @Override
    public void registerObserver(BaseObserver o) {
        Log.d("Execute", "registerObserver: ");
        foreignKeys.add((SFKView) o);
    }
    
    @Override
    public void removeObserver(BaseObserver o) {
        Log.d("Execute", "removeObserver: " + o.toString());
        foreignKeys.remove((SFKView) o);
    }
    
    @Override
    public void notifyObservers() {
        Log.d("Execute", "notifyObservers: ");
        STableDataBuffer sTableDataBuffer = new STableDataBuffer();
        for(SFKView sfk : foreignKeys){
            sfk.updateObserver(this, sTableDataBuffer);
        }
        
        for(int i = 0; i < sTableDataBuffer.getCount(); i++){
            Pair<SFKView, SFKView> curValue = sTableDataBuffer.getBuffer().get(i);
            
            //destroying the observer, NOTE removeObserver is called from inside the destroy method
            Objects.requireNonNull(curValue).first.destroy();
        }
    }

    public String getTitle() {
        return pojo.getTitle();
    }

    public void setTitle(String title) {
        pojo.setTitle(title);
    }

    public void setItems(List<SItemData> itemDataArrayList) {
        pojo.setItems(itemDataArrayList);
    }
}
